#' Loss operation
#'
#' @description
#' Binary operation method for character
#' @param lhs numeric or character
#' @param rhs numeric or character
#' @return
#' For numeric, compute division. Otherwise, misclassification.
#' @details
#' This function can deal with both regression and classification problem.
#' @export
`%m%` <- function(lhs, rhs) {
  if (is.numeric(lhs) & is.numeric(rhs)) {
    lhs - rhs
  } else {
    lhs == rhs
  }
}

#' In-Sample Error
#'
#' @description
#' This function computes an in-sample error in MC simulation setting
#' @param data MC data set generated by \code{\link{mc_data}}.
#' @param ny the number of response at each x point
#' @param fit True model function with \code{x}-named argument.
#' @param mod
#' @details
#' In-sample error differs from Expected test error in that it is computed in the same predictor values.
#' Instead, it uses new response values at each predictor point.
#' \deqn{Err_{in} = \frac{1}{N} \sum_{i = 1}^N E_{y_0} [L(Y_i^{(0)}, \hat{f}(x_i)) \mid T]}
#' @references Hastie, T., Tibshirani, R.,, Friedman, J. (2001). \emph{The Elements of Statistical Learning}. New York, NY, USA: Springer New York Inc..
#' @export
compute_insample <- function(data, ny, fit, mod) {
  cols1 <- paste0("y", 1:ny)
  cols2 <- paste0("fx", 1:ny)

}
