#' Generate Monte Carlo Samples
#'
#' @description
#' This function generates \code{\link[data.table]{data.table}} which consists of Monte Carlo sets.
#' @param rand Random sample generator function with parameter n
#' @param N Sample size in each MC sample
#' @param M Number of MC samples
#' @param char Indicator for MC sample, "s" by default. Distinguished by suffix number.
#' @param ... additional arguments for \code{rand}
#' @return
#' \code{data.table} with two columns. \code{x} is generated samples and \code{mc} indicates the MC sample.
#' @details
#' This function prepares for \code{data.table} group operation.
#' By grouping \code{mc} column, MC simulation can be easily done.
#' @export
mc_data <- function(rand, N = 100, M = 1000, char = "s", ...) {
  data.table::data.table(
    x = rand(n = N * M, ...),
    mc = gl(M, k = N, labels = paste0(char, 1:M))
  )
}

#' Generate Response
#'
#' @description
#' This function generates the response variable using true model assumed.
#' @param data MC data set generated by \code{\link{mc_data}}.
#' @param fit True model function with \code{x}-named argument.
#' @param rand Random sample generator function for error term. By default, \link[stats]{rnorm}
#' @return
#' Add two columns named \code{fx}, a true function value and \code{y}, error added.
#' @import data.table
#' @export
gen_y <- function(data, fit, rand, ...) {
  data %>%
    data.table() %>%
    .[,
      fx := fit(x)] %>%
    .[,
      y := fx + rand(.N, ...),
      by = mc] %>%
    .[]
}

#' Train and Predict a Model in each MC Sample
#'
#' @description
#' This function produces fitted values in each MC sample.
#' @param mod Model function.
#' @param formula an object of class \link[stats]{formula}.
#' @param data MC data set form of \code{\link{mc_data}}.
#' @param ... Additional arguments for \code{mod}
#' @return
#' The function adds a column named \code{pred} of which values are the fitted values from \code{mod}
#' @details
#' \code{mod} should have \code{formula} argument yet.
#' It uses predict.mod() function. Some class has an option called \code{type}. For example, \link[stats]{predict.glm}.
#' This function uses \code{type = "response"}.
#' Some model functions require \code{x} and \code{y}, so I will add that feature.
#' @import data.table
#' @importFrom rlang enquo
#' @export
pred_dt <- function(mod, formula, data, ...) {
  formul <- enquo(formula)
  data %>%
    data.table() %>%
    .[,
      pred :=
        mod(formula = formul, data = .SD, ...) %>%
        predict(type = "response"),
      by = mc] %>%
    .[]
}
